export const EXPERIENCES = [
  {
    id: 1,
    company: "Agendalo",
    location: "Lima, Perú",
    position: "Desarrollador Frontend",
    start: "Octubre 2022",
    end: "Presente",
    link: "https://agendalo.io/",
    tasks: [
      "Lideré el desarrollo frontend utilizando Nuxt.js",
      "Migración de la plataforma de una aplicación de una sola página (SPA) a renderización del lado del servidor (SSR) utilizando Nuxt.js",
      "Implementé prácticas de DevOps con Docker, GitHub Actions y AWS",
      "Integré autenticación OAuth2 para integración con Google y Microsoft",
      "Establecí pasarelas de pago con Mercado Pago, Niubiz y Stripe",
      "Desarrollé un panel administrativo para gestión de recursos y resolución de problemas de usuarios",
      "Colaboré con el CTO en la creación de bibliotecas internas utilizando React, Vue 3 y servicios de AWS",
    ],
  },
  {
    id: 3,
    company: "Gestión y Sistemas SAC",
    position: "Analista de Desarrollo Junior",
    start: "Diciembre 2020",
    end: "Julio 2021",
    tasks: [
      "Utilicé Angular y Azure DevOps para el desarrollo frontend y la entrega continua",
      "Desarrollé un panel administrativo para la gestión interna de comisiones en Banco Ripley",
      "Contribuí al desarrollo de un panel administrativo para la gestión interna de parámetros en Banco Falabella",
      "Desarrollé un portal de proveedores para The Leaf Company (ACS) y una aplicación de planificación de actividades",
    ],
  },
  {
    id: 2,
    company: "Ripley Peru - Gestión y Sistemas SAC",
    position: "Analista de Desarrollo Junior",
    start: "Agosto 2021",
    end: "Julio 2022",
    tasks: [
      "Colaboré en el desarrollo frontend para Homebanking y Plataforma de Pagos utilizando Angular e Ionic",
      "Colaboré estrechamente con equipos de pago en Perú y Chile a través de la metodología SCRUM",
      "Utilicé Bitbucket y Jenkins para la implementación de aplicaciones web",
      "Realicé análisis de incidentes para implementar mejoras y nuevas características",
    ],
  },
  {
    id: 4,
    company: "Movify",
    location: "Área Metropolitana de Lima",
    position: "Desarrollador de Software",
    start: "Junio 2020",
    end: "Julio 2021",
    tasks: [
      "Actué como Desarrollador Full Stack",
      "Responsable del desarrollo del sistema de cotización y pedidos para el equipo de ventas y mudanzas",
      "Desarrollé la arquitectura utilizando Vue.js para el lado del cliente y Spring Boot con Java para el lado del servidor",
      "Generé PDFs de cotizaciones y pedidos de ventas para clientes utilizando AWS Lambda",
      "Creé un módulo de cotización web para generar clientes potenciales utilizando un plugin de WordPress con servicios de AWS Lambda",
      "Desarrollé un módulo de informes para medir la eficacia del equipo de ventas",
    ],
  },
];
