export const EXPERIENCES = [
  {
    id: 1,
    company: "Agendalo",
    location: "Lima, Perú",
    position: "Frontend Developer",
    start: "October 2022",
    end: "Present",
    link: "https://agendalo.io/",
    tasks: [
      "Led frontend development using Nuxt.js",
      "Migration of the platform from a single-page application (SPA) to server-side rendering (SSR) using Nuxt.js",
      "Implemented DevOps practices with Docker, GitHub Actions, and AWS",
      "Integrated OAuth2 authentication for Google and Microsoft integration",
      "Established payment gateways with Mercado Pago, Niubiz, and Stripe",
      "Developed administrative panel for resource management and user issue resolution",
      "Collaborated with CTO in creating internal libraries using React, Vue 3, and AWS services",
    ],
  },
  {
    id: 2,
    company: "Ripley Peru - Gestión y Sistemas SAC",
    position: "Junior Developer Analyst",
    start: "August 2021",
    end: "July 2022",
    tasks: [
      "Led frontend development for Homebanking and Payment Platform using Angular and Ionic",
      "Collaborated closely with payment teams in Peru and Chile through SCRUM methodology",
      "Utilized Bitbucket and Jenkins for web application deployment",
      "Conducted incident analysis to implement improvements and new features",
    ],
  },
  {
    id: 3,
    company: "Gestión y Sistemas SAC",
    position: "Junior Developer Analyst",
    start: "December 2022",
    end: "July 2022",
    tasks: [
      "Utilized Angular and Azure DevOps for frontend development and continuous delivery",
      "Developed administrative panel for internal commission management at Banco Ripley",
      "Contributed to the development of administrative panel for internal parameter management at Banco Falabella",
      "Developed a supplier portal for The Leaf Company (ACS) and an activity planning application",
    ],
  },
  {
    id: 4,
    company: "Movify",
    location: "Lima Metropolitan Area",
    position: "Software Developer",
    start: "June 2020",
    end: "July 2021",
    tasks: [
      "Acted as a Full Stack Developer",
      "Responsible for developing the quotation and order system for the sales and moving team",
      "Developed architecture using Vue.js for the client-side and Spring Boot with Java for the server-side",
      "Generated PDFs of quotations and sales orders for customers using AWS Lambda",
      "Created a web quoting module to generate leads using a WordPress plugin with AWS Lambda services",
      "Developed a reporting module to measure the effectiveness of the sales team",
    ],
  },
];
