export const WORK_EXPERIENCES = [
  {
    id: 1,
    company: "Indra",
    location: "Lima, Perú",
    position: "Backend Developer AWS Senior",
    start: "Septiembre 2024",
    end: "Presente",
    tasks: [
      "Desarrollé microservicios en Java utilizando Spring Flux y Reactive para sistemas heredados",
      "Implementé microservicios con TypeScript, Node.js y Serverless Framework para la orquestación de sistemas heredados",
      "Gestioné bases de datos como PostgreSQL, DynamoDB y bases heredadas como IBM Informix",
      "Integré microservicios con servicios de AWS como Lambda, API Gateway, DynamoDB, PostgresRDS, SSM, Step Functions y EKS",
    ],
  },
  {
    id: 2,
    company: "Agendalo.io",
    location: "Lima, Perú",
    position: "Software Engineer Semi Senior",
    start: "Agosto 2022",
    end: "Julio 2024",
    link: "https://agendalo.io/",
    tasks: [
      "Lideré el desarrollo frontend utilizando Nuxt.js y apoyé en proyectos backend",
      "Migré una aplicación de una sola página (SPA) a renderización del lado del servidor (SSR) para mejorar el SEO",
      "Implementé pipelines CI/CD con contenedores, reduciendo los tiempos de entrega en un 20%",
      "Desarrollé autenticación OAuth2 para integración con Google y Microsoft",
      "Establecí pasarelas de pago con Mercado Pago, Niubiz y Stripe",
      "Desarrollé un panel administrativo para la gestión de recursos y resolución de problemas de usuarios mediante la API de WhatsApp",
      "Colaboré con el CTO para crear bibliotecas internas y migrar aplicaciones principales a un monorepo",
    ],
  },
  {
    id: 3,
    company: "Freelancer",
    location: "Remoto",
    position: "Desarrollador de Software",
    start: "Julio 2019",
    end: "Enero 2024",
    tasks: [
      "Desarrollé y mantuve proyectos de clientes, especializándome en tecnologías frontend y backend",
      "Trabajé con stacks tecnológicos como Java, Kotlin, JavaScript, TypeScript, Python, Vue.js, React, Angular, Spring Boot y Node.js",
      "Implementé APIs REST, GraphQL y protocolos de autenticación OAuth2",
      "Aproveché servicios de AWS como S3, EC2 y Lambda para soluciones escalables",
      "Configuré pipelines CI/CD utilizando Docker, GitHub Actions y GitLab",
      "Optimicé los procesos de desarrollo con metodologías ágiles y prácticas SCRUM",
      "Creé bibliotecas internas reutilizables para simplificar el desarrollo en múltiples proyectos",
    ],
  },  
  {
    id: 5,
    company: "Gestión y Sistemas SAC",
    location: "Lima, Perú",
    position: "Analista de Desarrollo Junior",
    start: "Agosto 2021",
    end: "Octubre 2022",
    tasks: [
      "Realicé desarrollo frontend utilizando Angular y gestioné repositorios con Azure DevOps",
      "Desarrollé paneles administrativos para la gestión interna de comisiones en Banco Ripley",
      "Contribuí al desarrollo de paneles administrativos para la gestión interna de parámetros en Banco Falabella",
      "Implementé un portal de proveedores para The Leaf Company (ACS) y una aplicación de planificación de actividades",
      "Colaboré estrechamente con equipos en Perú y Chile bajo metodología SCRUM",
    ],
  },
  {
    id: 5,
    company: "Banco Ripley Perú",
    location: "Lima, Perú",
    position: "Frontend Developer",
    start: "Agosto 2021",
    end: "Octubre 2022",
    tasks: [
      "Participé en el desarrollo frontend de la app de banca online multiplataforma y la plataforma de pagos",
      "Colaboré estrechamente con equipos de pagos en Perú y Chile bajo la metodología SCRUM",
      "Utilicé Angular e Ionic para el desarrollo de interfaces de usuario intuitivas",
      "Implementé widgets de autorización de transacciones e integré pasarelas de pago",
      "Realicé análisis de incidentes para implementar mejoras y nuevas características, trabajando en colaboración con el equipo de experiencia de usuario (UX)",
    ],
  },
];

export const EDUCATION_EXPERIENCES = [
  {
    id: 1,
    institution: "Universidad Nacional de Ingeniería",
    location: "Lima, Perú",
    degree: "Ingeniería de Sistemas",
    start: "2018",
    end: "2023",
    link: "https://www.uni.edu.pe/",
  },
];

export const COURSE_CERTIFICATIONS = [
  {
    id: 1,
    name: "Curso Profesional de DevOps",
    url: "https://platzi.com/p/franz.bendezu/curso/1431-devops/diploma/detalle/",
    date: "Noviembre 2023",
  },
  {
    id: 2,
    name: "Curso Profesional de Next.js",
    url: "https://platzi.com/p/franz.bendezu/curso/2707-profesional-nextjs/diploma/detalle/",
    date: "Noviembre 2023",
  },
  {
    id: 3,
    name: "Microsoft Certified: Azure Fundamentals",
    url: "https://credly.com/badges/108c4e3d-6a95-432c-8f82-53ff7dea4bb3",
    date: "Mayo 2023",
  },
  {
    id: 4,
    name: "CyberOps Associate",
    url: "https://credly.com/badges/4312c90f-a2b4-4ad8-bbb3-e7b873f86695",
    date: "Enero 2022",
  },
  {
    id: 5,
    name: "Curso Profesional de Arquitectura de Software",
    url: "https://platzi.com/p/franz.bendezu/curso/1248-pro-arquitectura/diploma/detalle/",
    date: "Octubre 2021",
  },
  {
    id: 6,
    name: "Curso Profesional de Scrum",
    url: "https://platzi.com/p/franz.bendezu/course/1750-scrum/diploma/detalle/",
    date: "Agosto 2021",
  },
  {
    id: 7,
    name: "Curso Profesional de Git y GitHub",
    url: "https://platzi.com/p/franz.bendezu/curso/1557-course/diploma/detalle/",
    date: "Agosto 2021",
  },
  {
    id: 8,
    name: "Programa Especializado - Google IT Automation with Python",
    url: "https://coursera.org/verify/professional-cert/EBQHHJ5LNUT5",
    date: "Junio 2020 - Julio 2020",
  },
  {
    id: 9,
    name: "Programa Especializado - Excel Skills for Business",
    url: "https://coursera.org/verify/specialization/Z88TCESL582W",
    date: "Agosto 2020 - Septiembre 2020",
  },
  {
    id: 10,
    name: "Programa Especializado - Google IT Support",
    url: "https://coursera.org/verify/professional-cert/AN72XYKRCANN",
    date: "Septiembre 2020 - Octubre 2020",
  },
];
