export const WORK_EXPERIENCES = [
  {
    id: 1,
    company: "Indra",
    location: "Lima, Perú",
    position: "Backend Developer AWS Senior",
    start: "Septiembre 2024",
    end: "Presente",
    tasks: [
      "Desarrollé microservicios en Java utilizando Spring Flux y Reactive para sistemas heredados",
      "Implementé microservicios con TypeScript, Node.js y Serverless Framework para la orquestación de sistemas heredados",
      "Gestioné bases de datos como PostgreSQL, DynamoDB y bases heredadas como IBM Informix",
      "Integré microservicios con servicios de AWS como Lambda, API Gateway, DynamoDB, PostgresRDS, SSM, Step Functions y EKS",
    ],
  },
  {
    id: 2,
    company: "Agendalo.io",
    location: "Lima, Perú",
    position: "Software Engineer Semi Senior",
    start: "Agosto 2022",
    end: "Julio 2024",
    link: "https://agendalo.io/",
    tasks: [
      "Lideré el desarrollo frontend utilizando Nuxt.js y apoyé en proyectos backend",
      "Migré una aplicación de una sola página (SPA) a renderización del lado del servidor (SSR) para mejorar el SEO",
      "Implementé pipelines CI/CD con contenedores, reduciendo los tiempos de entrega en un 20%",
      "Desarrollé autenticación OAuth2 para integración con Google y Microsoft",
      "Establecí pasarelas de pago con Mercado Pago, Niubiz y Stripe",
      "Desarrollé un panel administrativo para la gestión de recursos y resolución de problemas de usuarios mediante la API de WhatsApp",
      "Colaboré con el CTO para crear bibliotecas internas y migrar aplicaciones principales a un monorepo",
    ],
  },
  {
    id: 3,
    company: "Freelancer",
    location: "Remoto",
    position: "Desarrollador de Software",
    start: "Julio 2019",
    end: "Enero 2024",
    tasks: [
      "Desarrollé y mantuve proyectos de clientes, especializándome en tecnologías frontend y backend",
      "Trabajé con stacks tecnológicos como Java, Kotlin, JavaScript, TypeScript, Python, Vue.js, React, Angular, Spring Boot y Node.js",
      "Implementé APIs REST, GraphQL y protocolos de autenticación OAuth2",
      "Aproveché servicios de AWS como S3, EC2 y Lambda para soluciones escalables",
      "Configuré pipelines CI/CD utilizando Docker, GitHub Actions y GitLab",
      "Optimicé los procesos de desarrollo con metodologías ágiles y prácticas SCRUM",
      "Creé bibliotecas internas reutilizables para simplificar el desarrollo en múltiples proyectos",
    ],
  },
  {
    id: 4,
    company: "Gestión y Sistemas SAC",
    location: "Lima, Perú",
    position: "Analista de Desarrollo Junior",
    start: "Diciembre 2020",
    end: "Octubre 2022",
    tasks: [
      "Realicé desarrollo frontend utilizando Angular y gestioné repositorios con Azure DevOps",
      "Desarrollé paneles administrativos para la gestión interna de comisiones en Banco Ripley",
      "Contribuí al desarrollo de paneles administrativos para la gestión interna de parámetros en Banco Falabella",
      "Implementé un portal de proveedores para The Leaf Company (ACS) y una aplicación de planificación de actividades",
      "Colaboré estrechamente con equipos en Perú y Chile bajo metodología SCRUM",
    ],
  },
];

export const EDUCATION_EXPERIENCES = [
  {
    id: 1,
    institution: "Universidad Nacional de Ingeniería",
    location: "Lima, Perú",
    degree: "Ingeniería de Sistemas",
    start: "2018",
    end: "2023",
    link: "https://www.uni.edu.pe/",
  },
];
