import {
  IBaseProjectTechnology,
  IProjectTechonologyCategory,
} from "../interfaces/project";

export const PROJECT_TECHNOLOGY_CATEGORY: IProjectTechonologyCategory[] = [
  {
    name: "Cloud",
    value: "cloud",
  },
  {
    name: "Database",
    value: "database",
  },
  {
    name: "DevOps",
    value: "devops",
  },
  {
    name: "Testing",
    value: "testing",
  },
  {
    name: "Frontend Framework",
    value: "frontend-framework",
  },
  {
    name: "Backend Framework",
    value: "backend-framework",
  },
  {
    name: "Fullstack Framework",
    value: "fullstack-framework",
  },
  {
    name: "Web API",
    value: "web-api",
  },
  {
    name: "Programming Language",
    value: "programming-language",
  },
  {
    name: "IoT",
    value: "iot",
  },
  {
    name: "Content management system",
    value: "cms",
  },
];

export const PROJECT_TECHNOLOGIES: IBaseProjectTechnology[] = [
  {
    code: "nuxt",
    logo: "/assets/icons/nuxt.svg",
    name: "Nuxt",
    color: "#00C58E",
    categoryCodes: ["frontend-framework"],
  },
  {
    code: "typescript",
    logo: "/assets/icons/typescript.svg",
    name: "TypeScript",
    color: "#3178C6",
    categoryCodes: ["programming-language"],
  },
  {
    code: "graphql",
    logo: "/assets/icons/graphql.svg",
    name: "GraphQL",
    color: "#E535AB",
    categoryCodes: ["web-api"],
  },
  {
    code: "apollo-server",
    logo: "/assets/icons/graphql.svg",
    name: "Apollo Server",
    color: "#3B2E5A",
    categoryCodes: ["backend-framework"],
  },
  {
    code: "firebase",
    logo: "/assets/icons/firebase.svg",
    name: "Firebase",
    color: "#FFCA28",
    categoryCodes: ["cloud"],
  },
  {
    code: "vue2",
    logo: "/assets/icons/vue.svg",
    name: "Vue 2",
    color: "#4FC08D",
    categoryCodes: ["frontend-framework"],
  },
  {
    code: "vue3",
    logo: "/assets/icons/vue.svg",
    name: "Vue 3",
    color: "#4FC08D",
    categoryCodes: ["frontend-framework"],
  },
  {
    code: "cloud-functions",
    name: "Cloud Functions",
    color: "#FFD600",
    categoryCodes: ["devops"],
  },
  {
    code: "iot",
    name: "IoT",
    color: "#FFD600",
    categoryCodes: ["devops"],
  },
  {
    code: "lorawan",
    name: "LoRaWAN",
    color: "#FFD600",
    categoryCodes: ["devops"],
  },
  {
    code: "spring-boot",
    logo: "/assets/icons/spring.svg",
    name: "Spring Boot",
    color: "#6DB33F",
    categoryCodes: ["backend-framework"],
  },
  {
    code: "java",
    logo: "/assets/icons/java.svg",
    name: "Java",
    color: "#007396",
    categoryCodes: ["programming-language"],
  },
  {
    code: "kotlin",
    logo: "/assets/icons/kotlin.svg",
    name: "Kotlin",
    color: "#0095D5",
    categoryCodes: ["programming-language"],
  },
  {
    code: "postgresql",
    logo: "/assets/icons/postgresql.svg",
    name: "PostgreSQL",
    color: "#336791",
    categoryCodes: ["database"],
  },
  {
    code: "react",
    logo: "/assets/icons/react.svg",
    name: "React",
    color: "#61DAFB",
    categoryCodes: ["frontend-framework"],
  },
  {
    code: "tailwindcss",
    logo: "/assets/icons/tailwindcss.svg",
    name: "Tailwind CSS",
    color: "#38B2AC",
    categoryCodes: ["frontend-framework"],
  },
  {
    code: "javascript",
    logo: "/assets/icons/javascript.svg",
    name: "JavaScript",
    color: "#F7DF1E",
    categoryCodes: ["programming-language"],
  },
  {
    code: "nextjs",
    logo: "/assets/icons/nextjs_icon_dark.svg",
    name: "Next.js",
    color: "#000000",
    categoryCodes: ["frontend-framework"],
  },
  {
    code: "sass",
    name: "SASS",
    color: "#CC6699",
    categoryCodes: ["frontend-framework"],
  },
  {
    code: "prisma",
    logo: "/assets/icons/prisma.svg",
    name: "Prisma",
    color: "#CC6699",
    categoryCodes: ["backend-framework"],
  },
  {
    code: "aws-s3",
    name: "Amazon S3",
    logo: "/assets/icons/aws.svg",
    color: "#FFD600",
    categoryCodes: ["cloud"],
  },
  {
    code: "aws-ec2",
    name: "Amazon EC2",
    logo: "/assets/icons/aws.svg",
    color: "#FFD600",
    categoryCodes: ["cloud"],
  },
  {
    code: "amazon-rds",
    name: "Amazon RDS",
    logo: "/assets/icons/aws.svg",
    color: "#FFD600",
    categoryCodes: ["cloud"],
  },
  {
    code: "aws-amplify",
    name: "Amazon Amplify",
    logo: "/assets/icons/aws.svg",
    color: "#FFD600",
    categoryCodes: ["cloud"],
  },
  {
    code: "aws-lambda",
    name: "AWS Lambda",
    logo: "/assets/icons/aws.svg",
    color: "#FFD600",
    categoryCodes: ["cloud"],
  },
  {
    code: "bootstrap",
    name: "Bootstrap",
    logo: "/assets/icons/bootstrap.svg",
    color: "#6f2df4",
    categoryCodes: ["frontend-framework"],
  },
  {
    code: "wordpress",
    name: "Wordpress",
    logo: "/assets/icons/wordpress.svg",
    color: "#3858e9",
    categoryCodes: ["cms"],
  },
  {
    code: "nodejs",
    name: "Node",
    logo: "/assets/icons/nodejs.svg",
    color: "#3858e9",
    categoryCodes: ["database"],
  },
  {
    code: "spring-webflux",
    name: "Spring WebFlux",
    logo: "/assets/icons/spring.svg",
    color: "#6DB33F",
    categoryCodes: ["backend-framework"],
  },
  {
    code: "serverless-framework",
    name: "Serverless Framework",
    color: "#FD5750",
    categoryCodes: ["devops"],
  },
  {
    code: "dynamodb",
    name: "DynamoDB",
    logo: "/assets/icons/aws.svg",
    color: "#4053D6",
    categoryCodes: ["database"],
  },
  {
    code: "aws-api-gateway",
    name: "API Gateway",
    logo: "/assets/icons/aws.svg",
    color: "#FF4F8B",
    categoryCodes: ["cloud"],
  },
  {
    code: "aws-ssm",
    name: "AWS Systems Manager",
    logo: "/assets/icons/aws.svg",
    color: "#DD344C",
    categoryCodes: ["cloud"],
  },
  {
    code: "aws-step-functions",
    name: "AWS Step Functions",
    logo: "/assets/icons/aws.svg",
    color: "#FF4F8B",
    categoryCodes: ["cloud"],
  },
  {
    code: "aws-eks",
    name: "Amazon EKS",
    logo: "/assets/icons/aws.svg",
    color: "#FF9900",
    categoryCodes: ["cloud"],
  },
  {
    code: "oauth2",
    name: "OAuth 2.0",
    color: "#005C84",
    categoryCodes: ["web-api"],
  },
  {
    code: "mercado-pago",
    name: "Mercado Pago",
    color: "#009EE3",
    categoryCodes: ["web-api"],
  },
  {
    code: "niubiz",
    name: "Niubiz",
    color: "#6A1B9A",
    categoryCodes: ["web-api"],
  },
  {
    code: "stripe",
    name: "Stripe",
    color: "#635BFF",
    categoryCodes: ["web-api"],
  },
  {
    code: "whatsapp-api",
    name: "WhatsApp API",
    color: "#25D366",
    categoryCodes: ["web-api"],
  },
  {
    code: "python",
    name: "Python",
    color: "#3776AB",
    categoryCodes: ["programming-language"],
  },
  {
    code: "vue",
    name: "Vue",
    logo: "/assets/icons/vue.svg",
    color: "#4FC08D",
    categoryCodes: ["frontend-framework"],
  },
  {
    code: "angular",
    name: "Angular",
    color: "#DD0031",
    categoryCodes: ["frontend-framework"],
  },
  {
    code: "docker",
    name: "Docker",
    color: "#2496ED",
    categoryCodes: ["devops"],
  },
  {
    code: "github-actions",
    name: "GitHub Actions",
    color: "#2088FF",
    categoryCodes: ["devops"],
  },
  {
    code: "gitlab-ci",
    name: "GitLab CI/CD",
    color: "#FC6D26",
    categoryCodes: ["devops"],
  },
  {
    code: "azure-devops",
    name: "Azure DevOps",
    color: "#0078D7",
    categoryCodes: ["devops"],
  },
  {
    code: "ionic",
    name: "Ionic",
    color: "#3880FF",
    categoryCodes: ["frontend-framework"],
  },
  {
    code: "nestjs",
    name: "NestJS",
    color: "#E0234E",
    categoryCodes: ["backend-framework"],
  },
  {
    code: "kafka",
    name: "Apache Kafka",
    color: "#231F20",
    categoryCodes: ["backend-framework"],
  },
  {
    code: "redis",
    name: "Redis",
    color: "#DC382D",
    categoryCodes: ["database"],
  },
  {
    code: "eda",
    name: "Event-Driven Architecture",
    color: "#007E9B",
    categoryCodes: ["backend-framework"],
  },
  {
    code: "express",
    name: "Express",
    color: "#000000",
    categoryCodes: ["backend-framework"],
  },
  {
    code: "material-ui",
    name: "Material UI",
    color: "#007FFF",
    categoryCodes: ["frontend-framework"],
  },
  {
    code: "backstage",
    name: "Backstage",
    color: "#9BF0E1",
    categoryCodes: ["fullstack-framework"],
  },
  {
    code: "mariadb",
    name: "Mariadb",
    logo: "/assets/icons/mariadb.svg",
    color: "#3858e9",
    categoryCodes: ["database"],
  },
  {
    code: "mysql",
    name: "Mysql",
    logo: "/assets/icons/mysql.svg",
    color: "#3858e9",
    categoryCodes: ["database"],
  },
];
