import {
  IBaseProjectTechnology,
  IProjectTechonologyCategory,
} from "../interfaces/project";

export const PROJECT_TECHNOLOGY_CATEGORY: IProjectTechonologyCategory[] = [
  {
    name: "Cloud",
    value: "cloud",
  },
  {
    name: "Database",
    value: "database",
  },
  {
    name: "DevOps",
    value: "devops",
  },
  {
    name: "Testing",
    value: "testing",
  },
  {
    name: "Frontend Framework",
    value: "frontend-framework",
  },
  {
    name: "Backend Framework",
    value: "backend-framework",
  },
  {
    name: "Fullstack Framework",
    value: "fullstack-framework",
  },
  {
    name: "Web API",
    value: "web-api",
  },
  {
    name: "Programming Language",
    value: "programming-language",
  },
  {
    name: "IoT",
    value: "iot",
  },
  {
    name: "Content management system",
    value: "cms",
  },
];

export const PROJECT_TECHNOLOGIES: IBaseProjectTechnology[] = [
  {
    code: "nuxt",
    logo: "/assets/icons/nuxt.svg",
    name: "Nuxt",
    color: "#00C58E",
    categoryCodes: ["frontend-framework"],
  },
  {
    code: "typescript",
    logo: "/assets/icons/typescript.svg",
    name: "Typescript",
    color: "#3178C6",
    categoryCodes: ["programming-language"],
  },
  {
    code: "graphql",
    logo: "/assets/icons/graphql.svg",
    name: "GraphQL",
    color: "#E535AB",
    categoryCodes: ["web-api"],
  },
  {
    code: "apollo-server",
    logo: "/assets/icons/graphql.svg",
    name: "Apollo Server",
    color: "#3B2E5A",
    categoryCodes: ["backend-framework"],
  },
  {
    code: "firebase",
    logo: "/assets/icons/firebase.svg",
    name: "Firebase",
    color: "#FFCA28",
    categoryCodes: ["cloud"],
  },
  {
    code: "vue2",
    logo: "/assets/icons/vue.svg",
    name: "Vue 2",
    color: "#4FC08D",
    categoryCodes: ["frontend-framework"],
  },
  {
    code: "vue3",
    logo: "/assets/icons/vue.svg",
    name: "Vue 3",
    color: "#4FC08D",
    categoryCodes: ["frontend-framework"],
  },
  {
    code: "cloud-functions",
    name: "Cloud Functions",
    color: "#FFD600",
    categoryCodes: ["devops"],
  },
  {
    code: "iot",
    name: "LoT",
    color: "#FFD600",
    categoryCodes: ["devops"],
  },
  {
    code: "lorawan",
    name: "LoRaWAN",
    color: "#FFD600",
    categoryCodes: ["devops"],
  },
  {
    code: "spring-boot",
    logo: "/assets/icons/spring.svg",
    name: "Spring Boot",
    color: "#6DB33F",
    categoryCodes: ["backend-framework"],
  },
  {
    code: "java",
    logo: "/assets/icons/java.svg",
    name: "Java",
    color: "#007396",
    categoryCodes: ["programming-language"],
  },
  {
    code: "kotlin",
    logo: "/assets/icons/kotlin.svg",
    name: "Kotlin",
    color: "#0095D5",
    categoryCodes: ["programming-language"],
  },
  {
    code: "postgresql",
    logo: "/assets/icons/postgresql.svg",
    name: "PostgreSQL",
    color: "#336791",
    categoryCodes: ["database"],
  },
  {
    code: "react",
    logo: "/assets/icons/react.svg",
    name: "React",
    color: "#61DAFB",
    categoryCodes: ["frontend-framework"],
  },
  {
    code: "tailwindcss",
    logo: "/assets/icons/tailwindcss.svg",
    name: "Tailwind CSS",
    color: "#38B2AC",
    categoryCodes: ["frontend-framework"],
  },
  {
    code: "javascript",
    logo: "/assets/icons/javascript.svg",
    name: "Javascript",
    color: "#F7DF1E",
    categoryCodes: ["programming-language"],
  },
  {
    code: "nextjs",
    logo: "/assets/icons/nextjs_icon_dark.svg",
    name: "Next.js",
    color: "#000000",
    categoryCodes: ["frontend-framework"],
  },
  {
    code: "sass",
    logo: "/assets/icons/sass.svg",
    name: "SASS",
    color: "#CC6699",
    categoryCodes: ["frontend-framework"],
  },
  {
    code: "prisma",
    logo: "/assets/icons/prisma.svg",
    name: "Prisma",
    color: "#CC6699",
    categoryCodes: ["backend-framework"],
  },
  {
    code: "aws-s3",
    name: "Amazon S3",
    logo: "/assets/icons/aws.svg",
    color: "#FFD600",
    categoryCodes: ["cloud"],
  },
  {
    code: "aws-ec2",
    name: "Amazon EC2",
    logo: "/assets/icons/aws.svg",
    color: "#FFD600",
    categoryCodes: ["cloud"],
  },
  {
    code: "amazon-rds",
    name: "Amazon RDS",
    logo: "/assets/icons/aws.svg",
    color: "#FFD600",
    categoryCodes: ["cloud"],
  },
  {
    code: "aws-amplify",
    name: "Amazon Amplify",
    logo: "/assets/icons/aws.svg",
    color: "#FFD600",
    categoryCodes: ["cloud"],
  },
  {
    code: "aws-lambda",
    name: "AWS Lambda",
    logo: "/assets/icons/aws.svg",
    color: "#FFD600",
    categoryCodes: ["cloud"],
  },
  {
    code: "bootstrap",
    name: "Bootstrap",
    logo: "/assets/icons/bootstrap.svg",
    color: "#6f2df4",
    categoryCodes: ["frontend-framework"],
  },
  {
    code: "wordpress",
    name: "Wordpress",
    logo: "/assets/icons/wordpress.svg",
    color: "#3858e9",
    categoryCodes: ["cms"],
  },
  {
    code: "nodejs",
    name: "Node",
    logo: "/assets/icons/nodejs.svg",
    color: "#3858e9",
    categoryCodes: ["database"],
  },
  {
    code: "mariadb",
    name: "Mariadb",
    logo: "/assets/icons/mariadb.svg",
    color: "#3858e9",
    categoryCodes: ["database"],
  },
  {
    code: "mysql",
    name: "Mysql",
    logo: "/assets/icons/mysql.svg",
    color: "#3858e9",
    categoryCodes: ["database"],
  },
];
