name: CI Prod Pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  ci:
    uses: ./.github/workflows/ci.yml
    secrets:
      NEXT_PUBLIC_SPREE_ID: test-spree-id
      NEXT_PUBLIC_RECAPTCHA_ID: test-recaptcha-id
