name: CI Prod Pipeline

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  ci:
    uses: ./.github/workflows/ci.yml
    secrets:
      NEXT_PUBLIC_SPREE_ID: test-spree-id
      NEXT_PUBLIC_RECAPTCHA_ID: test-recaptcha-id
      PUBLIC_UMAMI_WEBSITE_ID: test-umami-website-id
