name: CI/CD Pipeline

on:
  workflow_dispatch: # This event allows you to manually trigger the workflow from the Actions tab

jobs:
  ci:
    uses: ./.github/workflows/ci.yml
    secrets:
      NEXT_PUBLIC_SPREE_ID: ${{ secrets.NEXT_PUBLIC_SPREE_ID }}
      NEXT_PUBLIC_RECAPTCHA_ID: ${{ secrets.NEXT_PUBLIC_RECAPTCHA_ID }}


  deploy:
    uses: ./.github/workflows/cd.yml
    secrets:
      NEXT_PUBLIC_SPREE_ID: ${{ secrets.NEXT_PUBLIC_SPREE_ID }}
      NEXT_PUBLIC_RECAPTCHA_ID: ${{ secrets.NEXT_PUBLIC_RECAPTCHA_ID }}
