name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:


jobs:
  ci:
    uses: ./.github/workflows/ci.yml
    secrets:
      NEXT_PUBLIC_SPREE_ID: ${{ secrets.NEXT_PUBLIC_SPREE_ID }}
      NEXT_PUBLIC_RECAPTCHA_ID: ${{ secrets.NEXT_PUBLIC_RECAPTCHA_ID }}


  deploy:
    needs: ci
    uses: ./.github/workflows/cd.yml
    secrets:
      NEXT_PUBLIC_SPREE_ID: ${{ secrets.NEXT_PUBLIC_SPREE_ID }}
      NEXT_PUBLIC_RECAPTCHA_ID: ${{ secrets.NEXT_PUBLIC_RECAPTCHA_ID }}
