name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions: {}

jobs:
  ci:
    permissions:
      contents: read
    uses: ./.github/workflows/ci.yml
    secrets:
      NEXT_PUBLIC_SPREE_ID: ${{ secrets.NEXT_PUBLIC_SPREE_ID }}
      NEXT_PUBLIC_RECAPTCHA_ID: ${{ secrets.NEXT_PUBLIC_RECAPTCHA_ID }}
      PUBLIC_UMAMI_WEBSITE_ID: ${{ secrets.PUBLIC_UMAMI_WEBSITE_ID }}

  cd:
    needs: ci
    permissions:
      contents: read
      pages: write
      id-token: write
    uses: ./.github/workflows/cd.yml
    secrets:
      NEXT_PUBLIC_SPREE_ID: ${{ secrets.NEXT_PUBLIC_SPREE_ID }}
      NEXT_PUBLIC_RECAPTCHA_ID: ${{ secrets.NEXT_PUBLIC_RECAPTCHA_ID }}
      PUBLIC_UMAMI_WEBSITE_ID: ${{ secrets.PUBLIC_UMAMI_WEBSITE_ID }}
